// Glossary of badminton terms; linkify() makes terms in questions and explanations tappable.
import { LANG } from '../state';
import type { Lang } from '../puzzles/types';

export const GLOSSARY: {k:string; de:string[]; en:string[]; fr:string[]; x?:boolean; t:Record<Lang,string>; d:Record<Lang,string>}[]=[
 {k:'clear',de:['Clear'],en:['clear'],fr:['dégagé'],t:{de:'Clear',en:'Clear',fr:'Dégagé'},d:{de:'Hoher, weiter Schlag von oben bis ins gegnerische Hinterfeld. Verschafft dir Zeit.',en:'A high, deep overhead shot to the opponent’s back court. Buys you time.',fr:'Coup haut et long frappé par le haut jusqu’au fond du terrain adverse. Te donne du temps.'}},
 {k:'lift',de:['Lift'],en:['lift'],fr:['lob'],t:{de:'Lift',en:'Lift',fr:'Lob'},d:{de:'Hoher Schlag von unten, meist aus dem Vorderfeld, bis ins gegnerische Hinterfeld. Ein Verteidigungsschlag.',en:'A high shot hit from below, usually from the forecourt, to the opponent’s back court. A defensive shot.',fr:'Coup haut frappé par en dessous, le plus souvent depuis l’avant du terrain, jusqu’au fond du terrain adverse. Un coup défensif.'}},
 {k:'smash',de:['Smash'],en:['smash'],fr:['smash'],t:{de:'Smash',en:'Smash',fr:'Smash'},d:{de:'Harter Schlag von oben steil nach unten. Der wichtigste Angriffsschlag.',en:'A hard overhead shot hit steeply down. The main attacking shot.',fr:'Coup puissant frappé par le haut, vers le bas avec une forte pente. Le principal coup d’attaque.'}},
 {k:'half',de:['Halbsmash'],en:['half smash'],fr:['demi-smash'],t:{de:'Halbsmash',en:'Half smash',fr:'Demi-smash'},d:{de:'Ein Smash mit weniger Kraft, dafür kontrollierter und oft steiler.',en:'A smash with less power, but more control and often steeper.',fr:'Un smash moins puissant, mais plus contrôlé et souvent plus plongeant.'}},
 {k:'drop',de:['Drop'],en:['drop'],fr:['amorti'],t:{de:'Drop',en:'Drop',fr:'Amorti'},d:{de:'Langsamer Schlag von oben, der knapp hinter dem Netz herunterfällt.',en:'A slow overhead shot that falls just behind the net.',fr:'Coup lent frappé par le haut, qui retombe juste derrière le filet.'}},
 {k:'net',de:['Netzdrop'],en:['net shot'],fr:['contre-amorti'],t:{de:'Netzdrop',en:'Net shot',fr:'Contre-amorti'},d:{de:'Kurzer Schlag am Netz, der knapp über die Netzkante geht und auf der anderen Seite herunterfällt.',en:'A short shot at the net that skims the tape and falls on the other side.',fr:'Coup court au filet qui rase la bande et retombe de l’autre côté.'}},
 {k:'drive',de:['Drive'],en:['drive'],fr:['drive'],t:{de:'Drive',en:'Drive',fr:'Drive'},d:{de:'Schneller, flacher Schlag etwa auf Netzhöhe, parallel zum Boden.',en:'A fast, flat shot at about net height, parallel to the floor.',fr:'Coup rapide et à plat, à peu près à hauteur du filet, parallèle au sol.'}},
 {k:'push',de:['Push'],en:['push'],fr:['poussette'],t:{de:'Push',en:'Push',fr:'Poussette'},d:{de:'Kurzer, flacher Schlag aus dem Vorderfeld ins gegnerische Mittelfeld.',en:'A short, flat shot from the forecourt into the opponent’s mid-court.',fr:'Coup court et à plat depuis l’avant du terrain vers le milieu du terrain adverse.'}},
 {k:'block',de:['Block'],en:['block'],fr:['bloc'],t:{de:'Block',en:'Block',fr:'Bloc'},d:{de:'Kurzer Abwehrschlag gegen einen Smash, der knapp hinter das Netz fällt.',en:'A short defensive reply to a smash that drops just behind the net.',fr:'Réponse défensive courte à un smash, qui retombe juste derrière le filet.'}},
 {k:'kill',de:['Kill'],en:['kill'],fr:['rush'],t:{de:'Kill',en:'Kill',fr:'Rush'},d:{de:'Harter Schlag nach unten aus Netznähe, der den Ballwechsel beendet.',en:'A hard downward shot near the net that ends the rally.',fr:'Coup puissant vers le bas près du filet, qui termine l’échange.'}},
 {k:'flick',de:['Flick'],en:['flick'],fr:['flick'],t:{de:'Flick',en:'Flick',fr:'Flick'},d:{de:'Aufschlag oder Schlag, der kurz aussieht, dann aber schnell hoch über den Gegner geht.',en:'A serve or shot that looks short but then goes quickly up and over the opponent.',fr:'Service ou coup qui a l’air court mais part vite en hauteur par-dessus l’adversaire.'}},
 {k:'tee',de:['T'],en:['T'],fr:['T'],x:true,t:{de:'T',en:'T',fr:'T'},d:{de:'Punkt, an dem vordere Aufschlaglinie und Mittellinie sich treffen. Im Doppel schlägt man meist von hier auf.',en:'The point where the short service line meets the centre line. In doubles you usually serve from here.',fr:'Le point où la ligne de service court croise la ligne médiane. En double, on sert le plus souvent d’ici.'}},
 {k:'tape',de:['Netzkante'],en:['tape'],fr:['bande'],t:{de:'Netzkante',en:'Tape',fr:'Bande du filet'},d:{de:'Oberkante des Netzes (1,55 m). Ist der Ball darüber, kannst du nach unten schlagen, darunter nicht.',en:'The top edge of the net (1.55 m). Above it you can hit down, below it you cannot.',fr:'Le bord supérieur du filet (1,55 m). Au-dessus, tu peux frapper vers le bas, en dessous non.'}},
 {k:'fore',de:['Vorderfeld'],en:['forecourt'],fr:['avant du terrain'],t:{de:'Vorderfeld',en:'Forecourt',fr:'Avant du terrain'},d:{de:'Bereich zwischen Netz und vorderer Aufschlaglinie.',en:'The area between the net and the short service line.',fr:'La zone entre le filet et la ligne de service court.'}},
 {k:'mid',de:['Mittelfeld'],en:['mid-court'],fr:['milieu du terrain','milieu de terrain'],t:{de:'Mittelfeld',en:'Mid-court',fr:'Milieu du terrain'},d:{de:'Mittlerer Bereich zwischen Vorderfeld und Hinterfeld.',en:'The middle area between forecourt and back court.',fr:'La zone centrale entre l’avant du terrain et le fond de court.'}},
 {k:'back',de:['Hinterfeld'],en:['back court'],fr:['fond de court'],t:{de:'Hinterfeld',en:'Back court',fr:'Fond de court'},d:{de:'Hinterer Bereich des Feldes bis zur Grundlinie.',en:'The rear area of the court up to the baseline.',fr:'La zone arrière du terrain, jusqu’à la ligne de fond.'}},
 {k:'fh',de:['Vorhand'],en:['forehand'],fr:['coup droit'],t:{de:'Vorhand',en:'Forehand',fr:'Coup droit'},d:{de:'Die Schlägerseite: für Rechtshänder rechts vom Körper.',en:'The racket side: for right-handers, to the right of the body.',fr:'Le côté de la raquette : pour un droitier, à droite du corps.'}},
 {k:'bh',de:['Rückhand'],en:['backhand'],fr:['revers'],t:{de:'Rückhand',en:'Backhand',fr:'Revers'},d:{de:'Die andere Seite: für Rechtshänder links vom Körper.',en:'The other side: for right-handers, to the left of the body.',fr:'L’autre côté : pour un droitier, à gauche du corps.'}},
 {k:'cross',de:['Cross'],en:['cross-court'],fr:['croisé'],t:{de:'Cross',en:'Cross-court',fr:'Croisé'},d:{de:'Diagonal über das Feld gespielt, statt gerade die Linie entlang.',en:'Played diagonally across the court instead of straight down the line.',fr:'Joué en diagonale à travers le terrain, au lieu du long de ligne.'}},
 {k:'fb',de:['vorne-hinten'],en:['front and back'],fr:['avant-arrière'],t:{de:'Vorne-hinten',en:'Front and back',fr:'Avant-arrière'},d:{de:'Angriffsaufstellung im Doppel: ein Spieler vorne am Netz, einer hinten.',en:'The attacking formation in doubles: one player at the net, one at the back.',fr:'La formation d’attaque en double : un joueur au filet, un au fond.'}},
 {k:'sbs',de:['nebeneinander'],en:['side by side'],fr:['côte à côte'],t:{de:'Nebeneinander',en:'Side by side',fr:'Côte à côte'},d:{de:'Verteidigungsaufstellung im Doppel: beide auf halber Tiefe, jeder deckt eine Seite.',en:'The defensive formation in doubles: both at mid depth, each covering one side.',fr:'La formation de défense en double : les deux à mi-profondeur, chacun couvre un côté.'}},
 {k:'rot',de:['Rotation'],en:['rotation'],fr:['rotation'],t:{de:'Rotation',en:'Rotation',fr:'Rotation'},d:{de:'Wechsel zwischen Angriff (vorne-hinten) und Verteidigung (nebeneinander) im Doppel.',en:'Switching between attack (front and back) and defence (side by side) in doubles.',fr:'Le passage entre attaque (avant-arrière) et défense (côte à côte) en double.'}},
 {k:'ssl',de:['Aufschlaglinie'],en:['short service line','service line'],fr:['ligne de service court','ligne de service'],t:{de:'Vordere Aufschlaglinie',en:'Short service line',fr:'Ligne de service court'},d:{de:'Linie 1,98 m vor dem Netz. Der Aufschlag muss dahinter landen.',en:'The line 1.98 m from the net. The serve has to land beyond it.',fr:'La ligne à 1,98 m du filet. Le service doit tomber au-delà.'}},
 {k:'base',de:['Grundlinie'],en:['baseline'],fr:['ligne de fond'],t:{de:'Grundlinie',en:'Baseline',fr:'Ligne de fond'},d:{de:'Die hintere Begrenzungslinie des Feldes.',en:'The back boundary line of the court.',fr:'La ligne qui limite le terrain à l’arrière.'}},
 {k:'centre',de:['Mittellinie'],en:['centre line'],fr:['ligne médiane'],t:{de:'Mittellinie',en:'Centre line',fr:'Ligne médiane'},d:{de:'Linie, die die beiden Aufschlagfelder trennt.',en:'The line that separates the two service courts.',fr:'La ligne qui sépare les deux zones de service.'}},
 {k:'frontp',de:['Vorderspieler','Netzspieler'],en:['front player','net player'],fr:['joueur avant','joueur au filet'],t:{de:'Vorderspieler',en:'Front player',fr:'Joueur avant'},d:{de:'Der Spieler, der im Angriff vorne am Netz steht.',en:'The player at the net when your team attacks.',fr:'Le joueur au filet quand ton équipe attaque.'}},
 {k:'backp',de:['Hinterspieler'],en:['back player'],fr:['joueur arrière'],t:{de:'Hinterspieler',en:'Back player',fr:'Joueur arrière'},d:{de:'Der Spieler, der im Angriff hinten steht und meist smasht.',en:'The player at the back when your team attacks, usually the one who smashes.',fr:'Le joueur au fond quand ton équipe attaque, le plus souvent celui qui smashe.'}},
 {k:'recv',de:['Rückschläger'],en:['receiver'],fr:['relanceur'],t:{de:'Rückschläger',en:'Receiver',fr:'Relanceur'},d:{de:'Der Spieler, der den Aufschlag annimmt.',en:'The player who receives the serve.',fr:'Le joueur qui reçoit le service.'}},
 {k:'ret',de:['Return'],en:['return of'],fr:['relance'],x:true,t:{de:'Return',en:'Return',fr:'Relance'},d:{de:'Der erste Schlag nach dem Aufschlag.',en:'The first shot after the serve.',fr:'Le premier coup après le service.'}},
 {k:'counter',de:['Konter'],en:['counter'],fr:['contre-attaque','en contre','contrer'],t:{de:'Konter',en:'Counter',fr:'Contre-attaque'},d:{de:'Ein schneller Gegenangriff aus der Verteidigung heraus.',en:'A fast counter-attack out of defence.',fr:'Une contre-attaque rapide depuis la défense.'}}
];
const GL_L='A-Za-zÄÖÜäöüß';
// French needs accented letters (é, à, ç …) as word characters too
const GL_LS: Record<Lang,string>={de:GL_L,en:GL_L,fr:'A-Za-zÀ-ÖØ-öø-ÿŒœ'};
const GLRX={} as Record<Lang,RegExp>;
(['de','en','fr'] as Lang[]).forEach(l=>{const GL_L=GL_LS[l];const alts: {v:string;x?:boolean}[]=[];GLOSSARY.forEach(g=>g[l].forEach(v=>alts.push({v,x:g.x})));
  alts.sort((a,b)=>b.v.length-a.v.length);
  GLRX[l]=new RegExp('(^|[^'+GL_L+'])('+alts.map(a=>a.v.replace(/[.*+?^${}()|[\]\\-]/g,'\\$&')+(a.x?'(?!['+GL_L+'])':'['+GL_L+']*')).join('|')+')','gi');});
function glKey(word: string){const w=word.toLowerCase();let best: string|null=null,len=0;
  GLOSSARY.forEach(g=>g[LANG].forEach(v=>{if(w.startsWith(v.toLowerCase())&&v.length>len){best=g.k;len=v.length;}}));return best;}
export function linkify(txt: string){if(!txt)return txt;const seen=new Set<string>();
  return txt.replace(GLRX[LANG],(all: string,pre: string,word: string)=>{const k=glKey(word);if(!k||seen.has(k))return all;seen.add(k);
    return pre+`<span role="button" tabindex="0" class="term" data-term="${k}">${word}</span>`;});}
